config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, :pieces
end

app/models/game.rb
class Game < ApplicationRecord
  attr_accessor :owner_id, :opponent_id, :turn

  belongs_to :owner, class_name: 'User'
  belongs_to :opponent, class_name: 'User', optional: true
  has_many :pieces

  scope :available, -> { where(Game.arel_table[:owner_id].not_eq(0)).where(opponent = nil) }

  def populate_game!
    Rook.create(game_id: self.id, moves: 0, position_x: 0, position_y: 0, color: "white", captured: false, user: owner)
    Knight.create(game_id: self.id, moves: 0, position_x: 1, position_y: 0, color: "white", captured: false, user: owner)
    Bishop.create(game_id: self.id, moves: 0, position_x: 2, position_y: 0, color: "white", captured: false, user: owner)
    King.create(game_id: self.id, moves: 0, position_x: 3, position_y: 0, color: "white", captured: false, user: owner)
    Queen.create(game_id: self.id, moves: 0, position_x: 4, position_y: 0, color: "white", captured: false, user: owner)
    Bishop.create(game_id: self.id, moves: 0, position_x: 5, position_y: 0, color: "white", captured: false, user: owner)
    Knight.create(game_id: self.id, moves: 0, position_x: 6, position_y: 0, color: "white", captured: false, user: owner)
    Rook.create(game_id: self.id, moves: 0, position_x: 7, position_y: 0, color: "white", captured: false, user: owner)

    (0..7).each do |n|
      Pawn.create(game_id: self.id, moves: 0, position_x: n, position_y: 1, color: "white", captured: false, user: owner)
    end

    Rook.create(game_id: self.id, moves: 0, position_x: 0, position_y: 7, color: "black", captured: false, user: opponent)
    Knight.create(game_id: self.id, moves: 0, position_x: 1, position_y: 7, color: "black", captured: false, user: opponent)
    Bishop.create(game_id: self.id, moves: 0, position_x: 2, position_y: 7, color: "black", captured: false, user: opponent)
    King.create(game_id: self.id, moves: 0, position_x: 3, position_y: 7, color: "black", captured: false, user: opponent)
    Queen.create(game_id: self.id, moves: 0, position_x: 4, position_y: 7, color: "black", captured: false, user: opponent)
    Bishop.create(game_id: self.id, moves: 0, position_x: 5, position_y: 7, color: "black", captured: false, user: opponent)
    Knight.create(game_id: self.id, moves: 0, position_x: 6, position_y: 7, color: "black", captured: false, user: opponent)
    Rook.create(game_id: self.id, moves: 0, position_x: 7, position_y: 7, color: "black", captured: false, user: opponent)

    (0..7).each do |n|
      Pawn.create(game_id: self.id, moves: 0, position_x: n, position_y: 6, color: "black", captured: false, user: opponent)
    end
  end

  def in_check?(king)
    in_check_pieces = []
    if king.color == 'black'
      color = 'white' 
    else
      color = 'black'
    end 

    opponent_pieces = self.pieces.where(color: color, captured: false)
    opponent_pieces.each do |piece|
      if piece.valid_move?(king.position_x, king.position_y)
        return true
        in_check_pieces << piece
      end 
    end 
    return false
  end 

  def is_occupied?(destination_x, destination_y)
    Piece.find_by(game_id: self, position_x: destination_x, position_y: destination_y).present?
  end


  def checkmate?(user)
    king = self.pieces.find_by(type: 'King', user: user, captured: false)

    # game not in check if king is not in check
    return false if !in_check?(king)

    # if in check, check possible moves the king can make and see if it will still keep the king in check, or if it can evade capture.
    king_x = king.position_x
    king_y = king.position_y
    available_king_moves = [[king_x + 1, king_y], [king_x - 1, king_y], [king_x, king_y + 1], [king_x, king_y - 1],
    [king_x + 1, king_y + 1], [king_x - 1, king_y - 1], [king_x + 1, king_y - 1], [king_x - 1, king_y + 1]]
   
    available_king_moves.each { |move|
     if king.valid_move?(move[0], move[1])
       king.move_to!(move[0], move[1])
       if ! self.in_check?(king)
         king.update_attributes(:position_x => king_x, :position_y => king_y)
         return false
       end
     end
    } 
    return true 
  end

  def set_turn!
    turn_id = self.owner.id.to_i
    self.update_attribute(turn: turn_id)
  end

  def update_turn!
    opponent = self.owner.id
    owner = self.owner.id
    if self.turn_id == owner 
      update_attributes(turn_id: opponent)
    else
      self.update_attributes(turn_id: owner)
    end

  end

  private

  def piece_params
    params.require(:piece).permit(:type, :position_x, :position_y, :game_id, :color, :captured, :image)
  end
end 

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :update, :show ]

  def index
    @games = Game.available
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    @game.update_attributes(:owner => current_user)
    @game.save!
    redirect_to root_path
  end

  def show
    @game = Game.find_by_id(params[:id])
    @pieces = Piece.where(game_id: @game)
    return render plain: "Not Found", status: :not_found if @game.blank? 
    redirect_to new_user_session_path if !user_signed_in?
  end
    

  def update
    @game = Game.find(params[:id])
    if @game.owner != current_user.id
      opponent = current_user
      set_turn = @game.owner.id.to_i
      @game.update_attributes(opponent: current_user, turn_id: set_turn)
      @game.populate_game!
      @game.save
      redirect_to game_path(@game)
    else
      render :index, status: :unprocessable_entity
    end
  end

private

  def game_params
    params.require(:game).permit(:name, :owner, :opponent, :game_id, :turn_id)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<br />
<br />
<br />
<style>
  body {background-color: #ECECEC;}
</style>
<div class = "game-header"><h1 class="game-title">Join A Game!</h1></div>
<br />
<br />
<div>
  <div class = "container">
    <div class = "row">
      <% @games.each do |game| %>
        <div class = "listed-game col-12 col-sm-4" id = 'game<%="#{game}"%>'>
          <%= game.name %>
          <%= link_to "Join", game_path(game), method: :put, class: "btn btn-success pull-right" %>
        </div>
      <% end %>
  </div>
</div>


<script>
  $(function() {
    $(window).ready(function(){
      $(window).scroll(function () {
        if ($(this).scrollTop() > 2) {
          $('.bg-dark').addClass('changeNavbarColor')
        }
        if ($(this).scrollTop() < 50) {
          $('.bg-dark').removeClass('changeNavbarColor')
        }
      });
    });
  });
</script>

<script>
  var colors = ['#5BC0EB', '#FDE74C', '#9BC53D'];
  var random_color = colors[Math.floor(Math.random() * colors.length)];

  $('.listed-game').css('background-color', random_color);
</script>

app/views/games/new.html.erb
<br />
<h1>Would you like to play a game?</h1>

<%= simple_form_for @game do |f| %>
  <%= f.input :name %>
  <br />
  <%= f.button :submit %>
<% end %>

app/views/games/show.html.erb
<br />
<br />
<br />
<style>
  body {background-color: #ECECEC;}
</style>
<div class = "game-header"><h1 class="game-title">Game No. <%=@game.id%></h1></div>

<div class = "container">
  <div class="row">
    <div class= "col-md-6">
      <table class = "chessboard" cellpadding="0" cellspacing="0">
        <% 7.downto(0) do |row| %>
          <tr> 
            <% 0.upto(7) do |column| %>
              <td id = 'pos<%= "#{column}_#{row}"%>' class = 'droppable'>    
                <% @pieces.each do |piece|%>
                  <div data-piece-id ="<%= piece.id %>">
                  <% if piece.position_y.to_i == row && piece.position_x.to_i == column %>
                    <%= link_to piece_path(piece) do %>
                      <%= image_tag(piece.show_image, class: "img-fluid draggable", 'data-piece-id': piece.id ,id:"piece#{column}_#{row}," ) %>
                    <% end %>
                  <% end %>
                  </div>
                <% end %>
            </td >          
            <% end %>
          </tr>
        <% end %>
        <br class="clr">
      </table>
    </div >
    <div class = "col-md-4">
      <div class = "game-details">
        <br />
        <% if @game.turn_id == current_user.id %>
          <h4> It's your turn! </h4>
        <% else %>
          <h4> Waiting for the other player's move... </h4>
        <% end %>
        <% if @game.owner == current_user %>
          <h6> You are the <strong>white</strong> player. </h6>
        <% elsif @game.opponent == current_user %>
          <h6> You are the <strong>black</strong> player. </h6>
        <% else %>
          <h6> You are not a player. </h6>
        <% end %>
      </div>
    </div>
  </div>
</div>


<% if @game.turn_id == current_user.id %>
  <script>
    $(function() {
      $(".draggable").draggable({
        containment: "table",
        snap: ".droppable",
        snapMode: "inner"
      });

      $(".droppable").droppable({
        drop: function( event, ui ){
          var initialId = ui.draggable.prop('id');
          var initial_x = initialId.substring(5, 6);
          var initial_y = initialId.substring(7);
          var targetId = event.target.id;
          var target_x = targetId.substring(3, 4);
          var target_y = targetId.substring(5);
          var newId = "piece" + target_x + "_" + target_y; 
          $(targetId).append(ui.draggable);
          $(ui.draggable).attr("id", newId);


          $.ajax({
            type: 'PUT',
            url: '/pieces/' + ui.draggable.data('piece-id') +'/',
            dataType: 'json',
            data: { piece: {position_x: target_x, position_y: target_y} },
            error: function() {
              location.reload(true);
            // if a move is not valid it will refresh the page
            }
          });
        }
      });
    });
  </script> 
<% end %>

<script>
  $(function() {
    $(window).ready(function(){
      $(window).scroll(function () {
        if ($(this).scrollTop() > 2) {
          $('.bg-dark').addClass('changeNavbarColor')
        }
        if ($(this).scrollTop() < 50) {
          $('.bg-dark').removeClass('changeNavbarColor')
        }
      });
    });
  });
</script>