config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, :pieces
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess Boxing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-sm navbar-light fixed-top bg-dark">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path do %>
      <span class = "navbar-brand"><i class="fas fa-chess"></i>&nbsp;Chess Boxing</span>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Available Games", games_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Start A Game", new_game_path, class: "nav-link", data: {toggle: 'modal', target:'#newGameModal'} %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.username, '#', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link", data: {toggle: 'modal', target:'#logInModal'}  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info", data: {toggle: 'modal', target:'#signUpModal'} %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>


  <!-- Sign Up Modal -->
  <div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="signUpModalLabel">Sign Up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
            <div class="field">
              <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email Address", data: { id:"user_email1"} %>
            </div>
            <br />
            <div class="field">
              <%= f.text_field :username, autocomplete: "username", placeholder: "Username" %>
            </div>
            <br />
            <div class="field">
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
            </div>
            <br />
            <div class="field">
              <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Repeat Password" %>
            </div>
            <br />
            <div class="actions">
              <%= f.submit "Sign up", class: 'btn btn-success pull-right' %>
            </div>
          <% end %>
          <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>

  <!-- Log In Modal -->
  <div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="loginModalLabel">Log In</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email or Username", data: { id:"user_email3"}%>
            </div>
            <br />
            <div class="field">
              <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <span><%= f.check_box :remember_me %>
                <%= f.label :remember_me %></span>
              </div>
            <% end -%>
            <br />
            <div class="actions">
              <%= f.submit "Log in", class: 'btn btn-success pull-right' %>
            </div>
          <% end %>
          <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>

  <!-- New Game Modal -->
  <div class="modal fade" id="newGameModal" tabindex="-1" role="dialog" aria-labelledby="newGameModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="newGameModalLabel">Start a Game</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for Game.new do |f| %>
            <%= f.input :name, label: 'Give Your Game a Name: ' %>
            <br />
            <%= f.button :submit, class: 'btn btn-success pull-right'%>
          <% end %>
          <small>Note: After you start your game, you must await a an opponent. We'll let you know when a player joins!</small>
        </div>
      </div>
    </div>
  </div>


    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/layouts/show.erb
<div id="chessboard">
  <div>
    <div class="white_square" id="KR8"></div>
    <div class="black_square" id="KN8"></div>
    <div class="white_square" id="KB8"></div>
    <div class="black_square" id="K8"></div>
    <div class="white_square" id="Q8"></div>
    <div class="black_square" id="QB8"></div>
    <div class="white_square" id="QN8"></div>
    <div class="black_square" id="QR8"></div>
  </div>
  <div>
    <div class="black_square" id="KR7"></div>
    <div class="white_square" id="KN7"></div>
    <div class="black_square" id="KB7"></div>
    <div class="white_square" id="K7"></div>
    <div class="black_square" id="Q7"></div>
    <div class="white_square" id="QB7"></div>
    <div class="black_square" id="QN7"></div>
    <div class="white_square" id="QR7"></div>
  </div>
  <div>
    <div class="white_square" id="KR6"></div>
    <div class="black_square" id="KN6"></div>
    <div class="white_square" id="KB6"></div>
    <div class="black_square" id="K6"></div>
    <div class="white_square" id="Q6"></div>
    <div class="black_square" id="QB6"></div>
    <div class="white_square" id="QN6"></div>
    <div class="black_square" id="QR6"></div>
  </div>
  <div>
    <div class="black_square" id="KR5"></div>
    <div class="white_square" id="KN5"></div>
    <div class="black_square" id="KB5"></div>
    <div class="white_square" id="K5"></div>
    <div class="black_square" id="Q5"></div>
    <div class="white_square" id="QB5"></div>
    <div class="black_square" id="QN5"></div>
    <div class="white_square" id="QR5"></div>
  </div>
  <div>
    <div class="white_square" id="KR4"></div>
    <div class="black_square" id="KN4"></div>
    <div class="white_square" id="KB4"></div>
    <div class="black_square" id="K4"></div>
    <div class="white_square" id="Q4"></div>
    <div class="black_square" id="QB4"></div>
    <div class="white_square" id="QN4"></div>
    <div class="black_square" id="QR4"></div>
  </div>
  <div>
    <div class="black_square" id="KR3"></div>
    <div class="white_square" id="KN3"></div>
    <div class="black_square" id="KB3"></div>
    <div class="white_square" id="K3"></div>
    <div class="black_square" id="Q3"></div>
    <div class="white_square" id="QB3"></div>
    <div class="black_square" id="QN3"></div>
    <div class="white_square" id="QR3"></div>
  </div>
  <div>
    <div class="white_square" id="KR2"></div>
    <div class="black_square" id="KN2"></div>
    <div class="white_square" id="KB2"></div>
    <div class="black_square" id="K2"></div>
    <div class="white_square" id="Q2"></div>
    <div class="black_square" id="QB2"></div>
    <div class="white_square" id="QN2"></div>
    <div class="black_square" id="QR2"></div>
  </div>
  <div>
    <div class="black_square" id="KR1"></div>
    <div class="white_square" id="KN1"></div>
    <div class="black_square" id="KB1"></div>
    <div class="white_square" id="K1"></div>
    <div class="black_square" id="Q1"></div>
    <div class="white_square" id="QB1"></div>
    <div class="black_square" id="QN1"></div>
    <div class="white_square" id="QR1"></div>
  </div>
</div>